// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnaDmN7jBsV_xLNt_OfK10N5yaD0fcwas',
    appId: '1:172805905929:web:36a8243f33cb6298a6a2d8',
    messagingSenderId: '172805905929',
    projectId: 'modul3-bde6d',
    authDomain: 'modul3-bde6d.firebaseapp.com',
    storageBucket: 'modul3-bde6d.appspot.com',
    measurementId: 'G-SQE3V2L9KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdiMImb9Xz5o7_5uUGknmnhfsYeIDYIZw',
    appId: '1:172805905929:android:bd1439900726d200a6a2d8',
    messagingSenderId: '172805905929',
    projectId: 'modul3-bde6d',
    storageBucket: 'modul3-bde6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-tM4EiC4WPzYL7GWhD08HVXWgW_nfn-c',
    appId: '1:172805905929:ios:2c6632cfab64ce9ea6a2d8',
    messagingSenderId: '172805905929',
    projectId: 'modul3-bde6d',
    storageBucket: 'modul3-bde6d.appspot.com',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-tM4EiC4WPzYL7GWhD08HVXWgW_nfn-c',
    appId: '1:172805905929:ios:0ad59e27f58cb023a6a2d8',
    messagingSenderId: '172805905929',
    projectId: 'modul3-bde6d',
    storageBucket: 'modul3-bde6d.appspot.com',
    iosBundleId: 'com.example.hotelBookingApp.RunnerTests',
  );
}
